### PR TITLE
Add 10 minute timeout to HTTPClient

### LINKED ISSUE #1060: Update-PSResource timeout
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

Beta 20 `Update-PSResource` times out while updating. In addition to that it does not respond to `CTRL+C`.

```
Update-PSResource -PassThru
Update-PSResource: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
```

### Expected behavior

```console
# updates modules
```

### Actual behavior

```console
Update-PSResource: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
```

### Error details

```console
Exception             :
    Type              : System.Threading.Tasks.TaskCanceledException
    CancellationToken : System.Threading.CancellationToken
    TargetSite        :
        Name          : HandleFailure
        DeclaringType : System.Net.Http.HttpClient
        MemberType    : Method
        Module        : System.Net.Http.dll
    Message           : The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
    InnerException    :
        Type           : System.TimeoutException
        Message        : The operation was canceled.
        InnerException :
            Type              : System.Threading.Tasks.TaskCanceledException
            CancellationToken : System.Threading.CancellationToken
            TargetSite        :
                Name          : MoveNext
                DeclaringType : System.Net.Http.HttpConnection+ContentLengthReadStream+<CompleteCopyToAsync>d__5,
System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
                MemberType    : Method
                Module        : System.Net.Http.dll
            Message           : The operation was canceled.
            InnerException    :
                Type           : System.IO.IOException
                TargetSite     :
                    Name          : ThrowException
                    DeclaringType : System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs, System.Net.Sockets,
Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
                    MemberType    : Method
                    Module        : System.Net.Sockets.dll
                Message        : Unable to read data from the transport connection: The I/O operation has been aborted
because of either a thread exit or an application request..
                InnerException :
                    Type            : System.Net.Sockets.SocketException
                    Message         : The I/O operation has been aborted because of either a thread exit or an
application request.
                    SocketErrorCode : OperationAborted
                    ErrorCode       : 995
                    NativeErrorCode : 995
                    HResult         : -2147467259
                Source         : System.Net.Sockets
                HResult        : -2146232800
                StackTrace     :
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken
cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.In
t32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sou
rces.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sou
rces.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32
bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken
cancellationToken)
            Source            : System.Net.Http
            HResult           : -2146233029
            StackTrace        :
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken
cancellationToken)
   at System.Net.Http.HttpConnectionResponseContent.<SerializeToStreamAsync>g__Impl|6_0(Stream stream,
CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption
completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts,
CancellationToken originalCancellationToken)
        HResult        : -2146233083
    Source            : System.Net.Http
    HResult           : -2146233029
    StackTrace        :
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response,
CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption
completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts,
CancellationToken originalCancellationToken)
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.V2ServerAPICalls.SendV2RequestForContentAsync(HttpRequestMessage
message, HttpClient s_client)
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.V2ServerAPICalls.HttpRequestCallForContent(String requestUrlV2,
ExceptionDispatchInfo& edi)
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.V2ServerAPICalls.InstallName(String packageName, Boolean
includePrerelease, ExceptionDispatchInfo& edi)
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.InstallHelper.HttpInstallPackage(VersionType searchVersionType,
NuGetVersion specificVersion, VersionRange versionRange, String pkgNameToInstall, PSRepositoryInfo repository,
ServerApiCall currentServer, ResponseUtil currentResponseUtil, String tempInstallPath, Hashtable packagesHash,
ExceptionDispatchInfo& edi)
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.InstallHelper.HttpInstall(String[] pkgNamesToInstall,
PSRepositoryInfo repository, ServerApiCall currentServer, ResponseUtil currentResponseUtil, ScopeType scope, Boolean
skipDependencyCheck, FindHelper findHelper)
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.InstallHelper.ProcessRepositories(String[] repository, Boolean
trustRepository, Boolean skipDependencyCheck, ScopeType scope)
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.InstallHelper.InstallPackages(String[] names, VersionRange
versionRange, NuGetVersion nugetVersion, VersionType versionType, String versionString, Boolean prerelease, String[]
repository, Boolean acceptLicense, Boolean quiet, Boolean reinstall, Boolean force, Boolean trustRepository, Boolean
noClobber, Boolean asNupkg, Boolean includeXml, Boolean skipDependencyCheck, Boolean authenticodeCheck, Boolean
savePkg, List`1 pathsToInstallPkg, Nullable`1 scope, String tmpPath, HashSet`1 pkgsInstalled)
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.UpdatePSResource.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [Update-PSResource], TaskCanceledException
FullyQualifiedErrorId :
System.Threading.Tasks.TaskCanceledException,Microsoft.PowerShell.PowerShellGet.Cmdlets.UpdatePSResource
InvocationInfo        :
    MyCommand        : Update-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 4
    Line             : update-psResource -PassThru
    Statement        : update-psResource -PassThru
    PositionMessage  : At line:1 char:1
                       + update-psResource -PassThru
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : update-psResource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
7.4-preview2
beta20
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by alerickson**
# PR Summary
Add a 10 minute timeout to HTTPClient.
Remove duplicate HttpClient object in ContainerRegistryServerAPICalls class.
 

## PR Context
Resolves #1060 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

**Review by anamnavi — APPROVED** [review]
LGTM

**Comment by SydneyhSmith** [comment]
@alerickson will cherry pick change to exclude the container registry change for the 1.0.5 release

**Comment by GuillaumeBau** [comment]
Hello,
This PR break the #1599
In src/code/V2ServerAPICalls.cs line 78, the added line " _sessionClient = new HttpClient(handler);" break the code because #1599 already create the HttpClient line 45 and 51.
It's the same in src/code/V3ServerAPICalls.cs line 78.

I try to use a PAT token but it's not works like #1599.

@anamnavi or @alerickson, Can you confirm it ?

Thanks

**Comment by GuillaumeBau** [comment]
I have tried it on my local environment and I confirm that is correct (
although there was no doubt). 

Using a PAT works again :)

**Pull request merged**
