### PR TITLE
Add dotnet analyzers to .csproj

### PR DESCRIPTION
**Pull request by alerickson**
# PR Summary

Add source code analysis to .csproj
see: https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview?tabs=net-6
and https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#enablenetanalyzers

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

**Review by anamnavi — APPROVED** [review]

**Comment by adityapatwardhan** [comment]
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview?tabs=net-7#treat-warnings-as-errors

Look at this. Treat warnings as errors. This causes build breaks.

**Comment by alerickson** [comment]
@adityapatwardhan I assumed we'd want to treat warnings like errors so that we can address any issues immediately.  Should we not treat warnings like errors?

**Comment by adityapatwardhan** [comment]
I meant we want to have build breaks when there is a warning.

**Comment by alerickson** [comment]
Perfect, just pushed that change

**Comment by alerickson** [comment]
Closing for now since adding `CodeAnalysisTreatWarningsAsErrors` generates roughly 100+ errors 😅 

Will address the errors and then add the changes from this PR.

**Pull request closed without merging**
