### PR TITLE
Add `-AcceptLicense` to `Save-PSResource`

### LINKED ISSUE #1450: `Save-PSResource` doesn't have `-AcceptLicense`
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

`Microsoft.PowerShell.PSResource` v1.0.0:

* `Install-PSResource` does have `-AcceptLicense`
* `Save-PSResource` does not have `-AcceptLicense`

`PackageManagement` v1.4.8.1 `Save-Package` has `-AcceptLicense`.

`PowerShellGet` v2.2.5 `Save-Module` has `-AcceptLicense`.

### Expected behavior

`Microsoft.PowerShell.PSResource\Save-PSResource` should have `-AcceptLicense`.

### Actual behavior

`Microsoft.PowerShell.PSResource\Save-PSResource` does not currently have `-AcceptLicense`.

### Error details

No error.

### Environment data

`Microsoft.PowerShell.PSResource` v1.0.0
PowerShell v7.3.8
Windows 11

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by o-l-a-v**
# PR Summary

Fixes #1450, but:

* Tests likely requires more work as `Save-PSResource` accepted license by default previously:
  * <https://github.com/PowerShell/PSResourceGet/blob/fe9c4d685933d4626d0bc74b682c73a671216934/src/code/SavePSResource.cs#L291>
* Documentation for `Save-PSResource` must be updated, unless that happens automagically?

## PR Context

To fix said issue.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [x] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed]()
        - [x] Issue filed: <https://github.com/MicrosoftDocs/PowerShell-Docs-PSGet/issues/160>
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

**Comment by alerickson** [comment]
Hi @o-l-a-v  thanks for the PR, more than happy to update the other tests if you can give me permission to make changes to your branch.  Otherwise could you add the `-AcceptLicense` parameter to the previous `Save-PSResource` tests and have the new test verify that it does not save if `-AcceptLicense` is not passed in?

**Comment by o-l-a-v** [comment]
@alerickson This means you can push to this branch too, right? I ask because I don't know.

image

If you need written consent: I consent. 🙂

---

> Otherwise could you add the -AcceptLicense parameter to the previous Save-PSResource tests and have the new test verify that it does not save if -AcceptLicense is not passed in?

Only `test_module_with_license` should require `-AcceptLicense`, right? So adding `-AcceptLicense` to all other tests should not be neccessary?

**Comment by alerickson** [comment]
This PR looks good, just waiting on some CI issues to be resolved and then will merge in!

**Review by alerickson — APPROVED** [review]

**Pull request merged**
