### PR TITLE
Make delete more robust (fix #1662)

### LINKED ISSUE #1662: "The process cannot access the file" during `Save-PSResource`
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

```powershell
# Assets
$ModuleName = [string] 'AWSPowerShell.NetCore'
$SavePath   = [string] [System.IO.Path]::Combine(
    $env:LOCALAPPDATA,
    'Microsoft',
    'PowerShell',
    'Modules'
)

# Create $SavePath if it does not already exist
if (-not [System.IO.Directory]::Exists($SavePath)) {
    $null = [System.IO.Directory]::CreateDirectory($SavePath)
}

# Save module
Save-PSResource -Repository 'PSGallery' -TrustRepository -IncludeXml -SkipDependencyCheck -Path $SavePath -Name $ModuleName
```

Lately PSResourceGet has had problems installing [AWSPowerShell.NetCore](https://www.powershellgallery.com/packages/AWSPowerShell.NetCore) on my system. I use `Save-PSResource` because I want modules in user context, but not synced with OneDrive (Known Folder Move).

It seems that the installation succeeds, as in it managed to move all files to `-Path`. But then it fails at deleting the temp directory used for downloading and extracting the files.

If a service like an antimalware scan is the reason these files can't be deleted: Detect it and wait for it to finish? Or try twice, wait five seconds before second attempt?

### Expected behavior

PSResourceGet should succeed in deleting temp path.

### Actual behavior

PSResourceGet fails to delete temp path.

### Error details

```console
PS C:\Users\<redacted>> Save-PSResource -Repository 'PSGallery' -TrustRepository -IncludeXml -SkipDependencyCheck -Path 'C:\Users\<redacted>\AppData\Local\Microsoft\PowerShell\Modules' -Name 'awspowershell.netcore'
Save-PSResource: Unable to successfully install package 'AWSPowerShell.NetCore': 'The process cannot access the file 'C:\Users\<redacted>\AppData\Local\Temp\9ae5cbb5-18d0-4daf-ae7d-fd4abed1818d\awspowershell.netcore\4.1.597\AWSPowerShell.TypeExtensions.ps1xml' because it is being used by another process.'
Save-PSResource: Operation is not valid due to the current state of the object.
Save-PSResource: The process cannot access the file 'C:\Users\<redacted>\AppData\Local\Temp\9ae5cbb5-18d0-4daf-ae7d-fd4abed1818d\awspowershell.netcore\4.1.597\AWSSDK.AWSMarketplaceMetering.dll' because it is being used by another process.
Save-PSResource: Package(s) 'awspowershell.netcore' could not be installed from repository 'PSGallery'.
PS C:\Users\<redacted>> Save-PSResource -Repository 'PSGallery' -TrustRepository -IncludeXml -SkipDependencyCheck -Path 'C:\Users\<redacted>\AppData\Local\Microsoft\PowerShell\Modules' -Name 'awspowershell.netcore' -Verbose
VERBOSE: Attempting to search for packages in 'PSGallery'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'AWSPowerShell.NetCore', version: '4.1.597'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'AWSPowerShell.NetCore', version: '4.1.597'".
VERBOSE: Performing the operation "Save-PSResource" on target "Exit ShouldProcess".
VERBOSE: Installation source path is: 'C:\Users\<redacted>\AppData\Local\Temp\101cb6bc-d191-4747-a56f-4304b1bbe1eb\awspowershell.netcore\4.1.597'
VERBOSE: Installation destination path is: 'C:\Users\<redacted>\AppData\Local\Microsoft\PowerShell\Modules\AWSPowerShell.NetCore\4.1.597'
VERBOSE: Temporary module version directory is: 'C:\Users\<redacted>\AppData\Local\Temp\101cb6bc-d191-4747-a56f-4304b1bbe1eb\awspowershell.netcore\4.1.597'
VERBOSE: Attempting to delete with restore on failure.'C:\Users\<redacted>\AppData\Local\Microsoft\PowerShell\Modules\AWSPowerShell.NetCore\4.1.597'
VERBOSE: Attempting to move 'C:\Users\<redacted>\AppData\Local\Temp\101cb6bc-d191-4747-a56f-4304b1bbe1eb\awspowershell.netcore\4.1.597' to 'C:\Users\<redacted>\AppData\Local\Microsoft\PowerShell\Modules\AWSPowerShell.NetCore\4.1.597'
Save-PSResource: Unable to successfully install package 'AWSPowerShell.NetCore': 'The process cannot access the file 'C:\Users\<redacted>\AppData\Local\Temp\101cb6bc-d191-4747-a56f-4304b1bbe1eb\awspowershell.netcore\4.1.597\AWSPowerShellLegacyAliases.psm1' because it is being used by another process.'
Save-PSResource: Operation is not valid due to the current state of the object.
VERBOSE: Attempting to delete 'C:\Users\<redacted>\AppData\Local\Temp\101cb6bc-d191-4747-a56f-4304b1bbe1eb'
Save-PSResource: The process cannot access the file 'C:\Users\<redacted>\AppData\Local\Temp\101cb6bc-d191-4747-a56f-4304b1bbe1eb\awspowershell.netcore\4.1.597\AWSSDK.AppConfig.dll' because it is being used by another process.
Save-PSResource: Package(s) 'awspowershell.netcore' could not be installed from repository 'PSGallery'.
PS C:\Users\<redacted>> Save-PSResource -Repository 'PSGallery' -TrustRepository -IncludeXml -SkipDependencyCheck -Path 'C:\Users\<redacted>\AppData\Local\Microsoft\PowerShell\Modules' -Name 'awspowershell.netcore' -Verbose -Debug
DEBUG: In SavePSResource::ProcessSaveHelper()
DEBUG: In InstallHelper::BeginInstallPackages()
DEBUG: Parameters passed in >>> Name: 'awspowershell.netcore'; VersionRange: ''; NuGetVersion: ''; VersionType: 'NoVersion'; Version: ''; Prerelease: 'False'; Repository: 'PSGallery'; AcceptLicense: 'True'; Quiet: 'False'; Reinstall: 'True'; TrustRepository: 'True'; NoClobber: 'False'; AsNupkg: 'False'; IncludeXml 'True'; SavePackage 'True'; TemporaryPath ''; SkipDependencyCheck: 'True'; AuthenticodeCheck: 'False'; PathsToInstallPkg: 'C:\Users\<redacted>\AppData\Local\Microsoft\PowerShell\Modules'; Scope ''
DEBUG: In InstallHelper::ProcessRepositories()
VERBOSE: Attempting to search for packages in 'PSGallery'
DEBUG: In InstallHelper::InstallPackages()
DEBUG: In InstallHelper::InstallPackage()
DEBUG: In V2ServerAPICalls::FindName()
DEBUG: In V2ServerAPICalls::HttpRequestCall()
DEBUG: Request url is 'https://www.powershellgallery.com/api/v2/FindPackagesById()?$filter=Id+eq+%27awspowershell.netcore%27+and+IsLatestVersion&$inlinecount=allpages&id=%27awspowershell.netcore%27'

Confirm
Are you sure you want to perform this action?
Performing the operation "Save-PSResource" on target "Package to save: 'AWSPowerShell.NetCore', version: '4.1.597'".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): a
DEBUG: In V2ServerAPICalls::InstallVersion()
DEBUG: In V2ServerAPICalls::HttpRequestCallForContent()
DEBUG: Request url is 'https://www.powershellgallery.com/api/v2/package/AWSPowerShell.NetCore/4.1.597'
DEBUG: In InstallHelper::TryInstallToTempPath()
DEBUG: In InstallHelper::DeleteExtraneousFiles()
DEBUG: Deleting 'C:\Users\<redacted>\AppData\Local\Temp\757b37dd-9480-4a6d-938c-9e702e642d3d\awspowershell.netcore\4.1.597\AWSPowerShell.NetCore.nuspec'
DEBUG: Deleting 'C:\Users\<redacted>\AppData\Local\Temp\757b37dd-9480-4a6d-938c-9e702e642d3d\awspowershell.netcore\4.1.597\[Content_Types].xml'
DEBUG: Deleting 'C:\Users\<redacted>\AppData\Local\Temp\757b37dd-9480-4a6d-938c-9e702e642d3d\awspowershell.netcore\4.1.597\_rels'
DEBUG: Deleting 'C:\Users\<redacted>\AppData\Local\Temp\757b37dd-9480-4a6d-938c-9e702e642d3d\awspowershell.netcore\4.1.597\package'
DEBUG: In InstallHelper::CreateMetadataXMLFile()
DEBUG: In InstallHelper::TryMoveInstallContent()
DEBUG: In InstallHelper::MoveFilesIntoInstallPath()
VERBOSE: Installation source path is: 'C:\Users\<redacted>\AppData\Local\Temp\757b37dd-9480-4a6d-938c-9e702e642d3d\awspowershell.netcore\4.1.597'
VERBOSE: Installation destination path is: 'C:\Users\<redacted>\AppData\Local\Microsoft\PowerShell\Modules\AWSPowerShell.NetCore\4.1.597'
VERBOSE: Temporary module version directory is: 'C:\Users\<redacted>\AppData\Local\Temp\757b37dd-9480-4a6d-938c-9e702e642d3d\awspowershell.netcore\4.1.597'
VERBOSE: Attempting to delete with restore on failure.'C:\Users\<redacted>\AppData\Local\Microsoft\PowerShell\Modules\AWSPowerShell.NetCore\4.1.597'
VERBOSE: Attempting to move 'C:\Users\<redacted>\AppData\Local\Temp\757b37dd-9480-4a6d-938c-9e702e642d3d\awspowershell.netcore\4.1.597' to 'C:\Users\<redacted>\AppData\Local\Microsoft\PowerShell\Modules\AWSPowerShell.NetCore\4.1.597'
Save-PSResource: Unable to successfully install package 'AWSPowerShell.NetCore': 'The process cannot access the file 'C:\Users\<redacted>\AppData\Local\Temp\757b37dd-9480-4a6d-938c-9e702e642d3d\awspowershell.netcore\4.1.597\AWSPowerShell.TypeExtensions.ps1xml' because it is being used by another process.'
Save-PSResource: Operation is not valid due to the current state of the object.
VERBOSE: Attempting to delete 'C:\Users\<redacted>\AppData\Local\Temp\757b37dd-9480-4a6d-938c-9e702e642d3d'
Save-PSResource: The process cannot access the file 'C:\Users\<redacted>\AppData\Local\Temp\757b37dd-9480-4a6d-938c-9e702e642d3d\awspowershell.netcore\4.1.597\AWSSDK.ARCZonalShift.dll' because it is being used by another process.
Save-PSResource: Package(s) 'awspowershell.netcore' could not be installed from repository 'PSGallery'.
PS C:\Users\<redacted>> Get-Module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty…}
Binary     1.0.5                 Microsoft.PowerShell.PSResourceGet  {Find-PSResource, Get-InstalledPSResource, Get-PSResourceRepository, Get-PSScriptFileInfo…}
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object…}
Script     2.3.5                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandler…}

PS C:\Users\<redacted>>
```

### Environment data

* PowerShell v7.4.1 x64
* Windows 11 23H2
* Microsoft.PowerShell.PSResourceGet v1.0.5

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by o-l-a-v**
# PR Summary

Make delete more robust by trying multiple times before failing, to fix #1662.

## PR Context

In #1662 I experienced that PSResourceGet would fail to install modules because antimalware realtime scanners added file handles on files inside `%TEMP%` that were to be deleted.

I read here <https://stackoverflow.com/a/329502/9874541> that trying multiple times is a common approach for scenarios like these.

I then tried adapting the existing code to try multiple times on the step that sometimes failed.

I tried the code by building both `net472` and `netstandard2.0`, and I could no longer reproduce #1662.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

**Comment by o-l-a-v** [comment]
I'm no C# expert, I've tried my best to make the delete directory function more robust by trying multiple times. Source of inspiration:

* <https://stackoverflow.com/questions/929276/how-to-recursively-list-all-the-files-in-a-directory-in-c>

I've also tried to read up on the best way to wait a little between attempts. It's my understanding from what I've read that if function is not async, `Thread.Sleep()` is fine.

**Review by alerickson — APPROVED** [review]

**Comment by alerickson** [comment]
Thanks again @o-l-a-v!  Hopefully this will help a bit with the file access issues.  It's hard to completely resolve since we never know how long access will be blocked, but this will certainly help with the more short-term cases.

**Pull request merged**
