### PR TITLE
Editorial pass on cmdlet ref

### PR DESCRIPTION
**Pull request by sdwheeler**
Editorial pass on cmdlet ref

I have lots of notes and bugs to report as we review this PR.

### CODE REVIEW

**Comment by alerickson** [comment]
@sdwheeler if you have permission to merge, feel free to merge when you're done, otherwise just tag us and we can merge!  Thanks again!

**Comment by alerickson** [comment]
Also wanted to add that I am merging a PR that adds `ValueFromPipelineByPropertyName = true` to `Set-PSResource`.  Could you add this to the docs too @sdwheeler?

Edit: merged PR #705

**Comment by sdwheeler** [comment]
> Also wanted to add that I am merging a PR that adds `ValueFromPipelineByPropertyName = true` to `Set-PSResource`. Could you add this to the docs too @sdwheeler?

Done

**Comment by sdwheeler** [comment]
@alerickson I don't have merge rights. I am done with my edits for now. It is ready to merge when the build checks are complete.

**Pull request merged**
